"""Generate in-game raycast probes and compare their logged terrain hits.

This module NEVER runs inside Scrap Mechanic. The generated Lua is an
integration fragment for a user-controlled Game script, not an installed mod.
"""
from __future__ import annotations

from collections import defaultdict
from math import hypot, isfinite, sqrt
from statistics import mean, median


LOG_PREFIX = "ATLAS_GROUND,"
# Current in-game logs from Scrap Mechanic 1.0 use 'voxelTerrain' for
# voxel ground hits; earlier API documentation lists 'terrainSurface'.
# Restrict accepted ground hits to this explicit pair of type strings.
GROUND_HIT_TYPES = frozenset({"terrainSurface", "voxelTerrain"})


def _validated_ground_plan(plan: dict) -> tuple[int, list[dict]]:
    """Accept only a sufficiently anchored tile-world-probe JSON document."""
    if not isinstance(plan, dict):
        raise ValueError("plan must be a tile-world-probe JSON object")
    alignment = plan.get("alignment")
    if not isinstance(alignment, dict) or alignment.get("status") != (
        "two_or_more_independent_tunnel_anchors"
    ):
        raise ValueError(
            "plan lacks two independent saved tunnel anchors; "
            "run tile-world-probe against the matching tile instance"
        )
    world_id = plan.get("world_id")
    if type(world_id) is not int or world_id <= 0:
        raise ValueError("plan must specify a positive integer world_id")
    edge = plan.get("critical_edge")
    if not isinstance(edge, dict):
        raise ValueError("plan has no critical_edge; use tile-world-probe --edge")
    samples = edge.get("world_samples")
    if not isinstance(samples, list) or not 1 <= len(samples) <= 512:
        raise ValueError("plan must contain 1..512 world_samples")

    seen_xy: set[tuple[float, float]] = set()
    for index, sample in enumerate(samples):
        if not isinstance(sample, dict):
            raise ValueError(f"invalid sample {index}")
        xy = sample.get("world_xy")
        z = sample.get("estimated_surface_world_z")
        if not (
            isinstance(xy, (list, tuple))
            and len(xy) == 2
            and all(type(v) in (int, float) and isfinite(v) for v in xy)
            and type(z) in (int, float)
            and isfinite(z)
        ):
            raise ValueError(f"invalid world sample position {index}")
        key = (float(xy[0]), float(xy[1]))
        if key in seen_xy:
            raise ValueError(f"duplicate XY sample at index {index}")
        seen_xy.add(key)
    return world_id, samples


def render_ground_probe_lua(plan: dict) -> str:
    """Return callable Lua, using World userdata from a real game script."""
    world_id, samples = _validated_ground_plan(plan)
    coords = "\n".join(
        "    { x = %.6f, y = %.6f, predictedZ = %.6f },"
        % (
            item["world_xy"][0],
            item["world_xy"][1],
            item["estimated_surface_world_z"],
        )
        for item in samples
    )
    return f"""-- Generated by SM Atlas from independently matched saved tunnel sockets.
-- NOT a working standalone mod: load this code from a legitimate game script.
-- Run smAtlasGroundProbe(world) with an actual game World userdata.
-- The narrow casts are based on estimated voxel heights. Hits may miss
-- or hit a cave ceiling: inspect output and compare with a physical walk.
-- Never modify the original save or use a numeric world ID as userdata.

local atlasGroundSamples = {{
{coords}
}}

function smAtlasGroundProbe(world)
    if world == nil or world.id ~= {world_id} then
        sm.log.warning("ATLAS_GROUND_ERROR,wrong_world,expected={world_id}")
        return false
    end
    sm.log.info("ATLAS_GROUND_META,world={world_id},count={len(samples)}")
    for index, sample in ipairs(atlasGroundSamples) do
        local start = sm.vec3.new(sample.x, sample.y, sample.predictedZ + 1.0)
        local finish = sm.vec3.new(sample.x, sample.y, sample.predictedZ - 2.0)
        local hit, result = sm.physics.raycast(
            start, finish, nil, sm.physics.filter.terrainSurface, world
        )
        -- A fallback can diagnose a terrain asset intercepting the ray.
        -- Only terrainSurface results count toward terrain measurements.
        if not hit then
            hit, result = sm.physics.raycast(
                start, finish, nil, sm.physics.filter.allTerrain, world
            )
        end
        local hitFlag, z, nx, ny, nz, kind = 0, 0, 0, 0, 0, "miss"
        if hit and result ~= nil and result.valid then
            hitFlag = 1
            z = result.pointWorld.z
            nx = result.normalWorld.x
            ny = result.normalWorld.y
            nz = result.normalWorld.z
            kind = result.type or "unknown"
        end
        sm.log.info(string.format(
            "ATLAS_GROUND,%d,%d,%.6f,%.6f,%.6f,%d,%.6f,%.6f,%.6f,%.6f,%s",
            index - 1, hitFlag, sample.x, sample.y, sample.predictedZ,
            world.id, z, nx, ny, nz, tostring(kind)
        ))
    end
    return true
end
"""


def _parse_probe_logs(log: str) -> dict[int, dict[str, object]]:
    """Read copy-pasted game log lines containing ATLAS_GROUND records."""
    observations: dict[int, dict[str, object]] = {}
    for line in log.splitlines():
        offset = line.find(LOG_PREFIX)
        if offset < 0:
            continue
        record = line[offset:].strip()
        fields = record.split(",", 11)
        if len(fields) != 12:
            raise ValueError(f"expected 12 comma-separated fields: {record}")
        prefix, index, hit, x, y, predicted, world, z, nx, ny, nz, kind = fields
        try:
            i, flag, world_id = int(index), int(hit), int(world)
            numbers = [float(item) for item in (x, y, predicted, z, nx, ny, nz)]
        except ValueError as exc:
            raise ValueError(f"invalid ATLAS_GROUND record: {record}") from exc
        if (
            i < 0 or flag not in (0, 1) or world_id <= 0
            or not all(isfinite(item) for item in numbers)
        ):
            raise ValueError(f"invalid ATLAS_GROUND values at index {i}")
        if i in observations:
            raise ValueError(
                f"duplicate ATLAS_GROUND index {i}; "
                "supply only one probe run"
            )
        # Preserve original physics type, including unknown labels;
        # non-ground collisions are excluded during comparison.
        observations[i] = {
            "index": i,
            "hit": bool(flag),
            "x": numbers[0],
            "y": numbers[1],
            "predicted_z_log": numbers[2],
            "world_id": world_id,
            "hit_z": numbers[3] if flag else None,
            "normal": tuple(numbers[4:7]) if flag else None,
            "hit_type": kind,
        }
    if not observations:
        raise ValueError(
            "no ATLAS_GROUND records found; use the output of "
            "the generated Lua probe (not a saved-world report)"
        )
    return observations


def compare_ground_observations(plan: dict, log: str) -> dict[str, object]:
    """Compare upward terrain-surface/voxel hits; preserve other collisions."""
    world_id, samples = _validated_ground_plan(plan)
    observations = _parse_probe_logs(log)
    lines: list[dict[str, object]] = []
    errors: list[float] = []
    tracks = defaultdict(list)
    for index, sample in enumerate(samples):
        planned_xy = tuple(float(v) for v in sample["world_xy"])
        predicted_z = float(sample["estimated_surface_world_z"])
        record = observations.get(index)
        row = {
            "index": index,
            "world_xy": planned_xy,
            "predicted_z": predicted_z,
            "fraction": sample.get("fraction"),
            "lateral_offset_m": sample.get("lateral_offset_m"),
            "status": "not_sampled",
        }
        if record is not None:
            if record["world_id"] != world_id:
                raise ValueError(
                    f"game world {record['world_id']} does not match "
                    f"saved world {world_id}"
                )
            if (
                hypot(
                    record["x"] - planned_xy[0],
                    record["y"] - planned_xy[1],
                ) > 0.01
                or abs(record["predicted_z_log"] - predicted_z) > 0.01
            ):
                raise ValueError(
                    f"sample index {index} differs from plan coordinates; "
                    "regenerate Lua from the same plan"
                )
            if (
                record["hit"] and record["hit_type"] in GROUND_HIT_TYPES
                and record["normal"][2] <= 0.1
            ):
                row.update({
                    "status": "non_upward_terrain_surface_hit",
                    "hit_type": record["hit_type"],
                    "actual_z": record["hit_z"],
                    "normal_world": record["normal"],
                })
            elif record["hit"] and record["hit_type"] in GROUND_HIT_TYPES:
                error = record["hit_z"] - predicted_z
                errors.append(error)
                row.update({
                    "status": "terrain_surface_hit",
                    "actual_z": record["hit_z"],
                    "normal_world": record["normal"],
                    "raw_height_error_m": round(error, 6),
                })
                tracks[row["lateral_offset_m"]].append(row)
            else:
                row.update({
                    "status": (
                        "no_hit" if not record["hit"]
                        else "other_collision_type"
                    ),
                    "hit_type": record["hit_type"],
                    "actual_z": record["hit_z"],
                })
        lines.append(row)

    if any(i >= len(samples) for i in observations):
        raise ValueError("log includes sample indexes absent from the plan")

    bias = median(errors) if errors else None
    if bias is not None:
        for row in lines:
            if row["status"] == "terrain_surface_hit":
                row["height_error_minus_median_m"] = round(
                    row["raw_height_error_m"] - bias, 6
                )

    track_summaries = []
    for lateral, points in sorted(tracks.items()):
        points.sort(key=lambda p: p["fraction"])
        steps = []
        for a, b in zip(points, points[1:]):
            # Missing intermediate hits must not be treated as adjacent
            # quarter-metre measurements.
            if b["fraction"] - a["fraction"] > 0.250001:
                continue
            span = hypot(
                b["world_xy"][0] - a["world_xy"][0],
                b["world_xy"][1] - a["world_xy"][1],
            )
            if span > 1e-8:
                steps.append({
                    "from_index": a["index"],
                    "to_index": b["index"],
                    "observed_absolute_gradient": round(
                        abs(b["actual_z"] - a["actual_z"]) / span, 6
                    ),
                })
        track_summaries.append({
            "lateral_offset_m": lateral,
            "terrain_surface_hits": len(points),
            "adjacent_measured_segments": len(steps),
            "max_observed_absolute_gradient": (
                max(v["observed_absolute_gradient"] for v in steps)
                if steps else None
            ),
            "measured_segments": steps,
        })

    return {
        "world_id": world_id,
        "planned_points": len(samples),
        "logged_points": len(observations),
        "terrain_surface_hits": len(errors),
        "other_hits_or_misses": sum(
            row["status"] in (
                "no_hit", "other_collision_type",
                "non_upward_terrain_surface_hit",
            )
            for row in lines
        ),
        "non_upward_terrain_surface_hits": sum(
            row["status"] == "non_upward_terrain_surface_hit"
            for row in lines
        ),
        "not_sampled": sum(
            row["status"] == "not_sampled" for row in lines
        ),
        "measured_minus_predicted": {
            "median_offset_m": round(bias, 6) if bias is not None else None,
            "mean_error_m": round(mean(errors), 6) if errors else None,
            "rmse_m": round(
                sqrt(mean(value ** 2 for value in errors)), 6
            ) if errors else None,
            "max_absolute_error_m": round(
                max(abs(value) for value in errors), 6
            ) if errors else None,
            "max_residual_after_median_offset_m": round(
                max(abs(value - bias) for value in errors), 6
            ) if errors else None,
        },
        "track_summaries": track_summaries,
        "samples": lines,
        "interpretation": (
            "observed game physics if authentic in-game logs; "
            "terrain raycast alone does not prove character walkability"
        ),
    }
