"""Regenerate the compact browser tile catalog from the Python research snapshot.

Only catalog asset names are evidence-backed: names/tags are not walkability or
collision claims. The original third-party license stays in THIRD_PARTY_NOTICES.md.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from sm_atlas.underground_tile_metadata import UNDERGROUND_TILE_METADATA  # noqa: E402

PREFIX = "$SURVIVAL_DATA/Terrain/Tiles/underground/"
TARGET = ROOT / "web" / "tile-catalog.mjs"

HEADER = """// Generated by scripts/export_web_tile_catalog.py; do not edit manually.
// Metadata source: Python underground_tile_metadata.py (MIT-derived snapshot).
// See THIRD_PARTY_NOTICES.md. Asset names are NOT verified passage geometry.
const CATALOG = Object.freeze({
"""
FOOTER = """});

const TAG_PAIRS = [
  ["passage", "passage"], ["deposit", "deposit"], ["dungeon", "dungeon"],
  ["minerbot", "minerbot"], ["elevator", "elevator"],
  ["corralium", "corralium"], ["gold", "gold"], ["sapphire", "sapphire"],
  ["spark", "sparkstone"], ["potato", "potato"], ["crystal", "crystal"],
  ["cyrstal", "crystal"], ["formation", "formations"],
];

export function identifyTile(uuid) {
  if (typeof uuid !== "string") return null;
  const record = CATALOG[uuid.toLowerCase()];
  if (!record) return null;
  const [relativePath, catalogSize] = record;
  const normalized = "/" + relativePath.toLowerCase();
  const name = relativePath.split("/").at(-1);
  const loweredName = name.toLowerCase();
  const family = loweredName.includes("elevator") ? "elevator"
    : normalized.includes("/tunnelpocket/") ? "tunnel_pocket"
    : normalized.includes("/cave/") ? "cave"
    : normalized.includes("/pocket/") ? "pocket"
    : normalized.includes("/poi/") ? "poi" : "other";
  const tags = [...new Set(TAG_PAIRS.filter(([term]) =>
    loweredName.includes(term)).map(([, tag]) => tag))];
  const dimensionMatch = name.match(/_(\\d+)x(\\d+)x(\\d+)\\.tile$/i);
  const dimensions = dimensionMatch ? dimensionMatch.slice(1).map(Number) : null;
  return { uuid: uuid.toLowerCase(), name, family, tags, dimensions,
    catalogSize, relativePath, source: "catalog-snapshot" };
}

export const tileCatalogSize = Object.keys(CATALOG).length;
"""


def generate() -> str:
    rows = []
    for uuid, metadata in sorted(UNDERGROUND_TILE_METADATA.items()):
        path = metadata["path"]
        if not isinstance(path, str) or not path.startswith(PREFIX):
            raise ValueError(f"unexpected underground tile path for {uuid}: {path}")
        relative = path.removeprefix(PREFIX)
        size = metadata["size"]
        if not isinstance(size, int) or size <= 0:
            raise ValueError(f"invalid tile size for {uuid}")
        rows.append(f"  {json.dumps(uuid)}: {json.dumps([relative, size], separators=(",", ":"))},")
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Verify that the committed browser catalog is current")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print("Browser tile catalog is stale. Run "
                  "python scripts/export_web_tile_catalog.py")
            return 1
        print(f"Catalog matches Python source ({len(UNDERGROUND_TILE_METADATA)} entries)")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Updated {TARGET.relative_to(ROOT)} "
          f"({len(UNDERGROUND_TILE_METADATA)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
